" [vim-plug]
call plug#begin()

Plug 'dense-analysis/ale'
Plug 'ericbn/vim-solarized'
Plug 'tpope/vim-sensible'

call plug#end()

set background=dark
set termguicolors  " Required for Solarized.
colorscheme solarized
