##### zplug.

export ZPLUG_HOME="$(brew --prefix)/opt/zplug"
source "${ZPLUG_HOME}/init.zsh"

zplug "MichaelAquilina/zsh-you-should-use"
zplug "romkatv/powerlevel10k", as:theme, depth:1
zplug "plugins/git", from:oh-my-zsh

# Load this in the following order to avoid conflicts.
zplug "zsh-users/zsh-autosuggestions", from:github
zplug "zsh-users/zsh-syntax-highlighting", defer:2
zplug "jeffreytse/zsh-vi-mode"

zplug load

# Install missing plugins.
if ! zplug check --verbose; then
  printf "Install missing zplug plugins? [y/N]: "
  if read -q; then
    echo; zplug install
  fi
fi

##### zsh-syntax-highlighting.

ZSH_HIGHLIGHT_HIGHLIGHTERS+=(brackets)  # Highlight a few more elements.

##### zsh-autosuggestions.

# Change the highlight style which is otherwise not visible with Solarized.
ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE='fg=10'

##### fzf.

# Set up key bindings and fuzzy completion.
source <(fzf --zsh)

# Enable multi-select mode.
export FZF_DEFAULT_OPTS="--multi"

# Use `fd` since it's faster than `find` and ignore git hidden files.
export FZF_DEFAULT_COMMAND="fd --type f"

# Preview file content using `bat`.
export FZF_CTRL_T_OPTS="
  --walker-skip .git,node_modules,target
  --preview 'bat -n --color=always {}'
  --bind 'ctrl-/:change-preview-window(down|hidden|)'"

# CTRL-Y to copy the command into clipboard using `pbcopy`.
export FZF_CTRL_R_OPTS="
  --bind 'ctrl-y:execute-silent(echo -n {2..} | pbcopy)+abort'
  --color header:italic
  --header 'Press CTRL-Y to copy command into clipboard'"

# Print tree structure in the preview window.
export FZF_ALT_C_OPTS="
  --walker-skip .git,node_modules,target
  --preview 'tree -C {}'"

##### bat.

alias rcat="$(which cat)"
alias cat="$(which bat) -n"

##### 1Password.

eval "$(op completion zsh)"; compdef _op op
