# added by setup_fb4a.sh
export ANDROID_SDK=/opt/android_sdk
export ANDROID_NDK_REPOSITORY=/opt/android_ndk
export ANDROID_HOME=${ANDROID_SDK}
export PATH=${PATH}:${ANDROID_SDK}/emulator:${ANDROID_SDK}/tools:${ANDROID_SDK}/tools/bin:${ANDROID_SDK}/platform-tools

##### zplug.
export ZPLUG_HOME="$(brew --prefix)/opt/zplug"
source "${ZPLUG_HOME}/init.zsh"

zplug "mafredri/zsh-async", from:github
zplug "zsh-users/zsh-autosuggestions", from:github
zplug "zdharma/fast-syntax-highlighting", from:github, defer:2
zplug "softmoth/zsh-vim-mode", from:github
zplug "MichaelAquilina/zsh-you-should-use"
zplug "sindresorhus/pure", use:pure.zsh, from:github, as:theme

zplug load

# Install missing plugins.
if ! zplug check --verbose; then
  printf "Install missing zplug plugins? [y/N]: "
  if read -q; then
    echo; zplug install
  fi
fi

##### fzf.
source /opt/homebrew/opt/fzf/shell/key-bindings.zsh
source /opt/homebrew/opt/fzf/shell/completion.zsh

# Enable multi-select mode.
export FZF_DEFAULT_OPTS="--multi"

# Preview file content using `bat`.
export FZF_CTRL_T_OPTS="
  --walker-skip .git,node_modules,target
  --preview 'bat -n --color=always {}'
  --bind 'ctrl-/:change-preview-window(down|hidden|)'"

# CTRL-Y to copy the command into clipboard using `pbcopy`.
export FZF_CTRL_R_OPTS="
  --bind 'ctrl-y:execute-silent(echo -n {2..} | pbcopy)+abort'
  --color header:italic
  --header 'Press CTRL-Y to copy command into clipboard'"

# Print tree structure in the preview window.
export FZF_ALT_C_OPTS="
  --walker-skip .git,node_modules,target
  --preview 'tree -C {}'"
