# ~/.bashrc: executed by bash(1) for non-login shells.

# If not running interactively, don't do anything.
[ -z "$PS1" ] && return

# Don't put duplicate lines in the history. See bash(1) for more options
# ... or force ignoredups and ignorespace.
HISTCONTROL=ignoredups:ignorespace

# Append to the history file, don't overwrite it.
shopt -s histappend

# For setting history length see HISTSIZE and HISTFILESIZE in bash(1).
HISTSIZE=5000
HISTFILESIZE=2000

# Check the window size after each command and, if necessary,
# update the values of LINES and COLUMNS.
shopt -s checkwinsize

# Make less more friendly for non-text input files, see lesspipe(1).
[ -x /usr/bin/lesspipe ] && eval "$(SHELL=/bin/sh lesspipe)"

# Privilege Homebrew binaries.
if hash brew 2>/dev/null && [ -d "$(brew --prefix)/bin" ]; then
  export PATH="$(brew --prefix)/bin:$PATH"
fi
if hash brew 2>/dev/null && [ -d "$(brew --prefix)/share/man" ]; then
  export MANPATH="$(brew --prefix)/share/man:$MANPATH"
fi

# Privilege Homebrew's GNU coreutils.
if hash brew 2>/dev/null && [ -d "$(brew --prefix coreutils)/libexec/gnubin" ]; then
  export PATH="$(brew --prefix coreutils)/libexec/gnubin:$PATH"
fi
if hash brew 2>/dev/null && [ -d "$(brew --prefix coreutils)/libexec/gnuman" ]; then
  export MANPATH="$(brew --prefix coreutils)/libexec/gnuman:$MANPATH"
fi

# Bash completion.
if [ -f /etc/bash_completion ] && ! shopt -oq posix; then
  . /etc/bash_completion
elif hash brew 2>/dev/null && [ -f $(brew --prefix)/etc/bash_completion ]; then
  . $(brew --prefix)/etc/bash_completion
fi

# Tool-specific aliases and functions.
for f in ~/.bash/*.bashrc; do
  . $f
done

# PS1 definition.
if [ -f ~/.bash/bash_ps1 ] ; then
  . ~/.bash/bash_ps1
fi
