# ~/.bash_aliases: Alias definitions.

# Enable color support of ls and also add handy aliases.
if hash dircolors 2>/dev/null; then
  test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
  alias ls='ls --color=auto'

  alias grep='grep --color=auto'
  alias fgrep='fgrep --color=auto'
  alias egrep='egrep --color=auto'
fi

# Some more ls aliases.
alias ll='ls -alF'                            # long list
alias la='ls -A'                              # all but . and ..
alias l='ls -CF'                              #
alias lt='ls -ltr'                            # sort by date

# Interactive operation...
alias rm='rm -i'
alias cp='cp -i'
alias mv='mv -i'
alias dirs='dirs -v'

# Default to human readable figures.
alias df='df -h'
alias du='du -h'

# Misc :)
alias less='less -r'                          # raw control characters
alias whence='type -a'                        # where, of a sort

# Directory navigation
alias pu='pushd .'                            # push current directory to top of stack
alias po='popd .'                             # pop top of stack to current directory
alias ..='cd ..'

# Clipboard
if hash pbcopy 2>/dev/null; then
  alias clip="pbcopy"
elif hash xclip 2>/dev/null; then
  alias clip='xclip -selection clipboard'
fi

# Git
if hash git 2>/dev/null; then
  alias ga='git add'
  alias gb='git branch'
  alias gc='git commit'
  alias gco='git checkout'
  alias gd='git diff'
  alias gl='git log'
  alias gs='git status'
fi

# Maven
if hash mvn 2>/dev/null; then
  alias mvn=mvn-notify
fi
